openapi: 3.0.3
info:
  title: Sample
  version: 1.0.0
paths:
  /pet:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
    Id:
      type: string
    Unused:
      type: object
      properties:
        x:
          type: string
