openapi: 3.1.0
info:
  title: Polymorphic API
  version: 1.0.0

paths:
  /fooBar:
    post:
      summary: Accept a polymorphic Foo or Bar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Root"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Root"

components:
  schemas:
    Root:
      type: object
      properties:
        name:
          type: string
      required:
        - name
      discriminator:
        propertyName: name
        mapping:
          Foo: "#/components/schemas/Foo"
          Bar: "#/components/schemas/Bar"

    Foo:
      allOf:
        - $ref: "#/components/schemas/Root"
        - type: object
          properties:
            fooSpecific:
              type: string
          required:
            - fooSpecific

    Bar:
      allOf:
        - $ref: "#/components/schemas/Root"
        - type: object
          properties:
            barSpecific:
              type: integer
          required:
            - barSpecific
